spring:
  application:
    name: TicketBookingAPIGateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: TICKETBOOKINGSERVICE
              uri: lb://TICKETBOOKINGSERVICE
              predicates:
                - Path=/ticket/**
            - id: SEATSERVICE
              uri: lb://SEATSERVICE
              predicates:
                - Path=/seat/**
server:
  port: 8089


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/